app/words/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
import requests
from app.models import db, Word
from app.words.forms import WordForm
import re

words_blueprint = Blueprint('words', __name__)

def clean_text(text):
    # Remove formatting markers
    text = re.sub(r'{[^}]+}', '', text)
    return text

def extract_dt_sn(data):
    dt_sn_pairs = []

    def traverse(data, current_sn=None, level=1):
        if isinstance(data, dict):
            for key, value in data.items():
                if key == 'sn':
                    current_sn = value
                elif key == 'dt' and current_sn is not None:
                    for dt_item in value:
                        if isinstance(dt_item, list) and dt_item[0] == 'text':
                            clean_dt = clean_text(dt_item[1])
                            dt_sn_pairs.append((f"{level}-{current_sn}", clean_dt))
                else:
                    traverse(value, current_sn, level)
        elif isinstance(data, list):
            for item in data:
                traverse(item, current_sn, level+1)

    traverse(data)
    return dt_sn_pairs

def get_word_definition(word):
    api_key = current_app.config['MW_API_KEY']
    url = f"{current_app.config['MW_API_BASE_URL']}/{word}?key={api_key}"
    response = requests.get(url)

    if response.status_code != 200:
        return None, None, None

    data = response.json()

    if not data or not isinstance(data, list):
        return None, None, None  # Return None if the data is invalid

    word_data = data[0]  # Extract the first entry which contains the word data

    # Extract definitions
    dt_sn_pairs = extract_dt_sn(word_data)
    definitions = [(sn, dt) for sn, dt in dt_sn_pairs]

    # Extract pronunciations
    pronunciations = get_pronunciations(word_data)
    print(pronunciations)
    # Extract audio pronunciation URL
    audio_url = get_audio_pronunciation(word_data)

    return definitions, pronunciations, audio_url


def get_pronunciations(data):
    pronunciations = []
    if 'hwi' in data and 'prs' in data['hwi']:
        for pr in data['hwi']['prs']:
            if 'mw' in pr:
                pronunciations.append(pr['mw'])
    return pronunciations

def get_audio_pronunciation(data):
    # Extract the audio pronunciation URL from the API response
    if 'hwi' in data and 'prs' in data['hwi']:
        sound_name = data['hwi']['prs'][0]['sound']['audio']
        if sound_name:
            subdirectory = sound_name[:1] if sound_name[0].isalpha() else 'number'
            audio_url = f'https://media.merriam-webster.com/audio/prons/en/us/mp3/{subdirectory}/{sound_name}.mp3'
            return audio_url
    return "Audio pronunciation not available."

@words_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    # Handle the word search form submission
    form = WordForm()
    if form.validate_on_submit():
        word = form.word.data
        print(f"Searching for word: {word}") #debugging
        return redirect(url_for('words.results', word=word))
    return render_template('home.html', form=form)

@words_blueprint.route('/results/<word>')
def results(word):
    definitions, pronunciations, audio_url = get_word_definition(word)
    error_message = None  # Initialize error message variable
    
    if not definitions:
        error_message = f'No definition found for "{word}".'
    
    return render_template(
        'results.html',
        word=word,
        definitions=definitions,
        pronunciations=pronunciations,
        audio_url=audio_url,
        error_message=error_message
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SpeakPeak Dictionary{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('home') }}">SpeakPeak Dictionary</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </div>
        </div>
    </nav>
    <div class="container mt-5 pt-5">
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

    <script>
        {% block scripts %}
        {% endblock %}
    </script>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home - SpeakPeak Dictionary{% endblock %}

{% block content %}
<div class="home-container text-center d-flex justify-content-center align-items-center">
    <div class="overlay d-flex flex-column justify-content-center align-items-center">
        <img src="{{ url_for('static', filename='images/speakpeak-logo.png') }}" alt="SpeakPeak Logo" class="logo">
        <h1 class="display-4 mt-3">Welcome to SpeakPeak Dictionary</h1>
        <p class="lead">Your go-to resource for word meanings, definitions, and more.</p>
        <form class="form-inline justify-content-center mt-4" action="{{ url_for('words.search') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="input-group input-group-lg">
                {{ form.word(class="form-control", placeholder="Enter a word", aria_label="Search", required=true) }}
                <div class="input-group-append">
                    <button class="btn btn-success" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block style %}
.home-container {
    background-image: url("{{ url_for('static', filename='images/speakpeak-logo.png') }}");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    color: white;
    border-radius: 20px;
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.3);
}
.overlay {
    background: rgba(0, 0, 0, 0.6);
    background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.4));
    padding: 50px;
    border-radius: 20px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.7);
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
.logo {
    width: 150px;
    height: auto;
    animation: fadeIn 2s ease-in-out;
}
.home-container h1 {
    font-size: 3em;
    margin-bottom: 0.5em;
    animation: fadeInDown 1s ease-in-out;
}
.home-container p {
    font-size: 1.5em;
    animation: fadeInUp 1s ease-in-out;
}
.form-control {
    max-width: 500px;
    border: none;
    border-radius: 0;
    border-top-left-radius: 30px;
    border-bottom-left-radius: 30px;
}

.input-group-append .btn {
    border-radius: 0;
    border-top-right-radius: 30px;
    border-bottom-right-radius: 30px;
    border: none;
    background-color: #28a745;
    color: white;
    height: 50px;
}
.input-group-append .btn:hover {
    background-color: #218838;
    color: white;
}
.input-group-append .btn:focus, .form-control:focus {
    box-shadow: none;
}
@keyframes fadeIn {
    0% { opacity: 0; }
    100% { opacity: 1; }
}
@keyframes fadeInDown {
    0% { opacity: 0; transform: translateY(-20px); }
    100% { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInUp {
    0% { opacity: 0; transform: translateY(20px); }
    100% { opacity: 1; transform: translateY(0); }
}
{% endblock %}

app/templates/results.html
{% extends "base.html" %}

{% block title %}Results for "{{ word|capitalize }}" - SpeakPeak Dictionary{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="mt-4 text-primary">Results For "{{ word|capitalize }}"</h1>
        <a href="{{ url_for('home') }}" class="btn btn-primary mt-4">Search Again</a>
    </div>
    {% if pronunciations %}
        <h2>Pronunciations:</h2>
        <ul class="list-group mt-3">
            {% for pronunciation in pronunciations %}
                <li class="list-group-item">{{ pronunciation }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if definitions %}
        <div class="definitions mt-3 p-4">
            {% for definition in definitions %}
                {% set sn_parts = definition[0].split('-') %}
                <div class="definition-item mb-2 pb-2">
                    <span class="definition-sn text-primary font-weight-bold" data-level="{{ sn_parts[0] }}">{{ sn_parts[1] }}</span>
                    <span class="definition-dt text-dark mt-1">{{ definition[1] }}</span>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-danger">No definitions found.</p>
    {% endif %}
    {% if audio_url != "Audio pronunciation not available." %}
        <!-- Section for audio pronunciation button -->
        <div class="audio-pronunciation mt-3">
            <p>Click the button to hear the pronunciation:</p>
            <!-- Hidden input to store the audio URL -->
            <input type="hidden" id="audio-url" value="{{ audio_url }}">
            <!-- Button to trigger audio playback -->
            <button class="btn btn-primary" onclick="playAudio()">Play Pronunciation</button>
        </div>
    {% endif %}
</div>

<!-- Hidden audio player elements -->
<audio id="audio-player" controls style="display:none;">
    <source id="audio-source" src="" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>

{% endblock %}

{% block scripts %}

function playAudio() {
    // Get the audio URL from the hidden input field
    let audioUrl = document.getElementById('audio-url').value;
    console.log('Audio URL:', audioUrl); // Debug statement

    // Get the audio player and source elements
    let audioPlayer = document.getElementById('audio-player');
    let audioSource = document.getElementById('audio-source');
    
    if (audioSource) {
        // Set the audio source URL and play the audio
        audioSource.src = audioUrl;
        audioPlayer.load();
        audioPlayer.play();

        // Log a message when the audio playback ends
        audioPlayer.onended = function() {
            console.log('Audio playback ended.');
        };
    } else {
        // Log an error if the audio source element is not found
        console.error("audioSource is null");
    }
}

{% endblock %}



{% block style %}
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background: linear-gradient(to right, #ffecd2, #fcb69f);
        color: #333;
    }
    h1 {
        color: #3b5998;
    }
    .container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
        animation: fadeIn 1s ease-in-out;
    }
    .definitions {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .definition-item {
        display: flex;
        align-items: baseline;
        gap: 10px;
        padding: 10px;
        background-color: #f1f1f1;
        border-radius: 5px;
        margin-bottom: 8px;
        transition: background-color 0.3s ease;
    }
    .definition-item:hover {
        background-color: #e3e3e3;
    }
    .definition-sn {
        font-size: 1.1em;
        color: #3b5998;
    }
    .definition-dt {
        font-size: 1em;
    }
    .definition-sn[data-level="1"] {
        margin-left: 0;
    }
    .definition-sn[data-level="2"] {
        margin-left: 20px;
    }
    .definition-sn[data-level="3"] {
        margin-left: 40px;
    }
    .btn-primary {
        background-color: #28a745;
        border-color: #28a745;
        transition: background-color 0.3s ease, border-color 0.3s ease;
    }
    .btn-primary:hover {
        background-color: #218838;
        border-color: #1e7e34;
    }
    @keyframes fadeIn {
        0% { opacity: 0; transform: translateY(20px); }
        100% { opacity: 1; transform: translateY(0); }
    }
{% endblock %}